vitrina_brusnika/goods/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = "goods"

urlpatterns = [
    path('', views.index, name='index'),
    path('products/', views.products, name='products'),
    path('product/<slug:slug>/', views.product, name='product')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vitrina_brusnika/myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

vitrina_brusnika/vitrina_brusnika/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('myapp.urls')),
    path('', include('goods.urls', namespace='goods'))
]

vitrina_brusnika/goods/models.py
from django.db import models

Сhoice_CHOICES = (('Нет', 'Нет'), ('Да', 'Да'))

# Create your models here.
class Chapters(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=100, unique=True, blank=True, null=True, verbose_name='URL')

    class Meta:
            # db_table: 'Chapter'
            verbose_name='Статью'
            verbose_name_plural='Статья'

    def __str__(self):
        return self.name

class Categories(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=100, unique=True, blank=True, null=True, verbose_name='URL')
    chapter = models.ForeignKey(Chapters, on_delete=models.CASCADE, verbose_name='Категория')
    image = models.ImageField(upload_to='category_images', blank=True, null=True, verbose_name='Изображение')

    class Meta:
        verbose_name='Категорию'
        verbose_name_plural='Категории'

    def __str__(self):
        return f'{self.name} (категория: {self.chapter})'
    
class Goods(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=100, unique=True, blank=True, null=True, verbose_name='URL')
    info_4_search = models.CharField(max_length=150, default='', verbose_name='Отображаемая информация')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    image = models.ImageField(upload_to='goods_images', blank=True, null=True, verbose_name='Изображение')
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Цена')
    discount = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Скидка в %')
    choice = models.CharField(max_length=50, choices=Сhoice_CHOICES ,default="Нет", verbose_name='Новые товары')
    category = models.ForeignKey(to=Categories, on_delete=models.CASCADE, verbose_name='Категория')
    xs_count = models.PositiveIntegerField(default=0, verbose_name='Количество размера XS')
    s_count = models.PositiveIntegerField(default=0, verbose_name='Количество размера S')
    m_count = models.PositiveIntegerField(default=0, verbose_name='Количество размера M')
    l_count = models.PositiveIntegerField(default=0, verbose_name='Количество размера L')
    xl_count = models.PositiveIntegerField(default=0, verbose_name='Количество размера XL')
    
    

    class Meta:
        verbose_name='Товар'
        verbose_name_plural='Товары'

    def __str__(self):
        return self.name
    
    def display_id(self):
        return f'{self.id:05}'
    
    def sell_price(self):
        if self.discount:
            return round(self.price - (self.price*self.discount/100), 2)
        return self.price

vitrina_brusnika/goods/views.py
from django.shortcuts import render
from django.db.models import Q
from goods.models import Goods, Categories

# Create your views here.
def index(request):

    new_goods = Goods.objects.filter(choice = "Да")
    categories = Categories.objects.filter(Q(name = 'Зонты') | Q(name = 'Футболки'))

    context = {
        'title': 'Главная страница',
        'new_goods': new_goods,
        'categories': categories,
    }

    return render(request, 'goods/index.html', context)

def product(request, slug):
    product = Goods.objects.get(slug=slug)
    context = {
        'product': product
    }
    return render(request, 'goods/product.html', context)




def products(request):
    products = Goods.objects.all()

    context = {
        'products': products
    }

    return render(request, 'goods/products.html', context)

vitrina_brusnika/goods/templates/goods/index.html
{% extends 'base.html' %}
{% load static %}


{% block css %}{% static 'css/catalog.css'%}{% endblock %}
{% block title %}{{title}}{% endblock %}

{% block content %}

<!-- Начало переменной части -->
<div class="cetral-part">
    <!-- Картинка "Смотреть коллекци." -->
    <img class="main_img" src="{% static 'media/132_resized 1.png'%}" alt="liva">
    <a class="red_btn" href="">Смотреть коллекцию</a>
    <div class="middle_text_pos">
        <h3>НОВЫЕ ТОВАРЫ</h3>
        <a class="look_all_param" href="{% url 'goods:products' %}">Смотреть все</a>
    </div>

    <!-- Три картинки -->
    <goods class="main_offer">
        {% for product in new_goods %}
        <div class="">
            <a href="{% url "goods:product" product.slug %}"><img class="main_img" src="{{ product.image.url }}" alt={{ product.name }}></a>
            {% if product.discount %}
                <a href="{% url "goods:product" product.slug %}"><p class="offers-font">{{ product.name }}<br>
                <span class='discount'>{{product.price}}₽   </span>{{ product.sell_price }}₽</span></a>
            {% else %}
                <a href="{% url "goods:product" product.slug %}"><p class="offers-font">{{ product.name }}<br>{{ product.sell_price }}₽</a>
            {% endif%}
        </div>
        {% endfor%}
    </goods>

    <!-- Две картинки -->
    <div class="sec_offer">
        {% for category in categories %}
            <div>
                <a href="#"><img class="main_img" src="{{ category.image.url }}" alt={{ category.name }}></a>
                <a href="#"><p class="sec_offers_text">{{ category.name }}</p></a>
            </div>
        {% endfor%} 

    </div>
</div>
</div>
</section>
<!-- Конец переменной части -->

{% endblock %}

vitrina_brusnika/goods/templates/goods/product.html
{% extends 'base.html' %}
{% load static %}


{% block css %}{% static 'css/product.css'%}{% endblock %}
{% block title %}{{title}}{% endblock %}

{% block content %}

<!-- Начало переменной части -->
<div class="cetral-part">
    <h1 class="header_discr">{{ product.category.chapter }} / {{ product.category.name }}</h1>
    <div class="product_grid">
        <div class="left_grid">
            <img class="image_param" src="{{ product.image.url }}" alt="{{ product.name }}">
        </div>
        <div class="right_grid">
            <p class="product_name">{{ product.name }}</p>
            {% if product.discount %}
                <p class="disc_price"> {{product.price}}₽    <span class="sell_price">{{ product.sell_price }}₽</span></p>
            {% else %}
                <p class="price">{{product.price}}₽</p>
            {% endif %}
            <div class="sizes">
                <p>Размер:</p>
                <p class="table_size">Таблица размеров</p>
            </div>
            <div class="size">
                {% if product.xs_count %}
                    <a class="clickable first_size сlick_size" href="">XS</a>
                {% else %}
                    <p class="empty_good first_size">XS</p>
                {% endif %}
                {% if product.s_count %}
                    <a class="clickable sec_size сlick_size" href="">S</a>
                {% else %}
                    <p class="empty_good sec_size">S</p>
                {% endif %}
                {% if product.m_count %}
                    <a class="clickable sec_size сlick_size" href="">M</a>
                {% else %}
                    <p class="empty_good sec_size">M</p>
                {% endif %}
                {% if product.l_count %}
                    <a class="clickable sec_size сlick_size" href="">L</a>
                {% else %}
                    <p class="empty_good sec_size">L</p>
                {% endif %}
                {% if product.xl_count %}
                    <a class="clickable first_size сlick_size" href="">XL</a>
                {% else %}
                    <p class="empty_good first_size">XL</p>
                {% endif %}
            </div>
            <div class="description_chapter">
                <a class="add-bottom" href="#">Добавить в корзину</a> <!-- Еще нужно доработать!!!!! -->
                <p class="description_header">Описание</p>
                <p class="description">{{ product.description }}</p>
                <div class="details">
                    <a href="">Состав и детали</a> <!-- Еще нужно доработать!!!!! -->
                    <a href=""><img src="{% static 'media/other_images/Vector 84.svg'%}" alt=""></a>
                </div>
                <p class="line_between"></p>
                <div class="details">
                    <a href="">Доставка и оплата</a> <!-- Еще нужно доработать!!!!! -->
                    <a href=""><img src="{% static 'media/other_images/Vector 84.svg'%}" alt=""></a>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</section>
<!-- Конец переменной части -->

{% endblock %}

vitrina_brusnika/goods/templates/goods/products.html
{% extends 'base.html' %}
{% load static %}


{% block css %}{% static 'css/catalog.css'%}{% endblock %}
{% block title %}{{title}}{% endblock %}

{% block content %}

<!-- Начало переменной части -->
<div class="cetral-part">
    {% for product in products %}
    <a><img  src="{{ product.image.url }}" alt="logo"></a>
    {% endfor %}
    
</div>
</div>
</section>
<!-- Конец переменной части -->

{% endblock %}

vitrina_brusnika/templates/base.html
{% load static %}
{% load goods_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main_page.css'%}"> 
    <link rel="stylesheet" type="text/css" href="{% block css %}{% endblock %}"> 
    <title>{% block title %}Базовый шаблон{% endblock %}</title>
</head>
<body class="body">
    <header>
        <div class="header-container">
            <a href="{% url 'goods:index' %}"><img src="{% static 'media/logo.png'%}" alt="logo"></a>
            <nav class="header-nav-menu">
                <a class="nav_font_color" href="#">ЛИЧНЫЙ КАБИНЕТ</a>
                <a class="nav_font_color" href="#">ИЗБРАННОЕ <span style="color: red;">(0)</span></a>
                <a class="nav_font_color" href="#">КОРЗИНА <span style="color: red;">(0)</span></a>
            </nav>
            <div class="burger-but">
                <div>
                    <input type="checkbox" id="burger-checkbox" class="burger-checkbox">
                    <label for="burger-checkbox" class="burger"></label>
                    <ul class="menu-list">
                        <ul><a href="#" class="nav_font_color">ЛИЧНЫЙ КАБИНЕТ</a></ul>
                        <ul><a href="#" class="nav_font_color">ИЗБРАННОЕ <span style="color: red;">(0)</span></a></ul>
                        <ul><a href="#" class="nav_font_color">КОРЗИНА <span style="color: red;">(0)</span></a></ul>
                    </ul>
                </div>
            </div>
        </div>
    </header>
    <section>
        <div class="central-cont">
            {% comment %} Left bar {% endcomment %}
            <div class="left-bar">
                <div style="margin-top: 60px" class="loc_in_column">
                        {% tag_chapter as chapters %}
                        {% for chapter in chapters %}
                            <div class="category chek-pointer" data-target="products-{{ chapter.slug }}">
                                {{ chapter.name }}</div>
                            <div class="product-list loc_in_column" id="products-{{ chapter.slug }}">
                                {% tag_categories chapter.name as categories%}
                                {% for category in categories %}
                                    <ul class="sub_menu_param">
                                        <li><a href="#">{{ category.name }}</a></li>
                                    </ul>
                                {% endfor %}
                            </div>
                        {% endfor %}     
                </div>
            </div>
        {% comment %} Контент {% endcomment %}
        {% block content %}
            <div class="cetral-part"></div>
        </div>
    </section>
    
        {% endblock %}

        {% comment %} Footer {% endcomment %}
    <footer class="footer_grid footer_params">
        <main_label class="first_row">    
                <img class="main_img" src="{% static 'media/ВИТРИНА.БРУСНИКА.png'%}" alt="liva">
        </main_label>
        <first_menu class="loc_in_column sec_row_first_col">
            <a href="#">О нас</a>
            <a href="#">Контакты</a>
        </first_menu>
        <sec_menu class="loc_in_column sec_row_sec_col">
            <a href="#">Доставка и оплата</a>
            <a href="#">Обмен и возврат</a>
            <a href="#">Политика конфиденциальности</a>
            <a href="#">Публичная оферта</a>
        </sec_menu>
        <third_menu class="loc_in_column sec_row_third_col">
            <a href="#">Telegram</a>
            <a href="#">VK</a>
        </third_menu>
        <right_part class="loc_in_column sec_row_fourth_col">
            <p>Подпишитесь на нашу e-mail рассылку, чтобы<br>первыми увидеть новые коллекции, новости</p>
            <input style="font-size: medium;" type="email" placeholder="E-mail" id="email" name="email" />
            <a class="black_bottom" href="#">ПОДПИСАТЬСЯ</a>
        </right_part>
        <p class="last_row_left_part">2024 © Витрина Брусника</p>
        <p class="last_row_right_part">Создание сайта — Elpycode</p>
    </footer>
    <script type="text/javascript" src={% static "js/scripts.js" %}></script>
</body>
</html>